name: copy something from aggregation-pb
on:
  repository_dispatch:
    types: [target-updated]
jobs:
  copy-target:
    runs-on: ubuntu-20.04
    name: copy hello
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: clone aggregation-pb
        uses: actions/checkout@v2
        with:
          repository: Hirochon/aggregation-pb
          path: aggregation-pb
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: ls
        run: ls aggregation-pb
      - name: copy hello
        run: cp -r aggregation-pb/hello hello
      - name: clean aggregation-pb
        run: rm -rf aggregation-pb
      - name: create PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit-message: 'copy hello'
          branch: copy_target
          branch-suffix: timestamp
          delete-branch: true
          title: 'updated hello'