name: copy something from aggregation-pb
on:
  repository_dispatch:
    types: [target-updated]

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.1
        id: go
      - name: Check out
        uses: actions/checkout@v2
      # 処理を高速化するために環境をキャッシュ
      - name: Cache
        uses: actions/cache@v2.1.0
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

  copy-target:
    needs: setup
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: clone aggregation-pb
        uses: actions/checkout@v2
        with:
          repository: Hirochon/aggregation-pb
          path: aggregation-pb
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: copy hello
        run: cp -r aggregation-pb/hello hello
      - name: clean aggregation-pb
        run: rm -rf aggregation-pb
      - name: apt-get
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
      - name: initialize go
        run: go mod init github.com/Hirochon/chon-go-micro-packages
      - name: get protoc
        run: |
          go get -v google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
          go get -v google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
      - name: compile protocol-buffers
        run: |
          export PATH="$PATH:$(go env GOPATH)/bin"
          protoc --go_out=. --go_opt=paths=source_relative \
            --go-grpc_out=. --go-grpc_opt=paths=source_relative \
            hello/proto/hello.proto
      - name: create PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit-message: 'copy hello'
          branch: copy_target
          branch-suffix: timestamp
          delete-branch: true
          title: 'updated hello'